/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup/route'
import { Route as SigninRouteImport } from './routes/signin/route'
import { Route as ProfileRouteImport } from './routes/profile/route'
import { Route as FollowingsRouteImport } from './routes/followings/route'
import { Route as FollowersRouteImport } from './routes/followers/route'
import { Route as FavoritesRouteImport } from './routes/favorites/route'
import { Route as CreateRouteImport } from './routes/create/route'
import { Route as RecipeIdRouteImport } from './routes/$recipeId/route'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SignupRouteRoute = SignupRouteImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const SigninRouteRoute = SigninRouteImport.update({
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRouteRoute = ProfileRouteImport.update({
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const FollowingsRouteRoute = FollowingsRouteImport.update({
  path: '/followings',
  getParentRoute: () => rootRoute,
} as any)

const FollowersRouteRoute = FollowersRouteImport.update({
  path: '/followers',
  getParentRoute: () => rootRoute,
} as any)

const FavoritesRouteRoute = FavoritesRouteImport.update({
  path: '/favorites',
  getParentRoute: () => rootRoute,
} as any)

const CreateRouteRoute = CreateRouteImport.update({
  path: '/create',
  getParentRoute: () => rootRoute,
} as any)

const RecipeIdRouteRoute = RecipeIdRouteImport.update({
  path: '/$recipeId',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$recipeId': {
      preLoaderRoute: typeof RecipeIdRouteImport
      parentRoute: typeof rootRoute
    }
    '/create': {
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRoute
    }
    '/favorites': {
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRoute
    }
    '/followers': {
      preLoaderRoute: typeof FollowersRouteImport
      parentRoute: typeof rootRoute
    }
    '/followings': {
      preLoaderRoute: typeof FollowingsRouteImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  RecipeIdRouteRoute,
  CreateRouteRoute,
  FavoritesRouteRoute,
  FollowersRouteRoute,
  FollowingsRouteRoute,
  ProfileRouteRoute,
  SigninRouteRoute,
  SignupRouteRoute,
])

/* prettier-ignore-end */
